## Basic Configuration

baseurl = "https://timabe.info/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "tim abraham"
title = "tim abraham"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "timabe-me" 
googleAnalytics = "UA-73240359-1"
enableRobotsTXT = true

[permalinks]
post = "/:year/:month/:slug/"


## Site Settings
[params]
author = "tim abraham"
authorimage = "dot.png"
dateformat = "Jan 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "timabe"
linkedin = "timabraham"
twitter = "timabe"
email = "timmy4@gmail.com"
youtube = "TimAbraham"

## Extras
[params.extra]
copyright = "© 2023. Tim Abraham. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = false
highlightjs = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "cooking"
    identifier = "cook"
    weight = 2
    url = "/cook/"
[[menu.main]]
    name = "books"
    identifier = "books"
    weight = 3
    url = "/books/"
[[menu.main]]
    name = "blog"
    weight = 5
    identifier = "blog"
    url = "/blog/"
